import = [
  "~/.config/alacritty/themes/themes/ayu_dark.toml"
]

live_config_reload = true

[cursor]
style = "Block"
unfocused_hollow = true

[font]
size = 14.0

[font.normal]
family = "MesloLGMDZ Nerd font"

[[keyboard.bindings]]
chars = "º"
key = "Key0"
mods = "Alt"

[[keyboard.bindings]]
chars = "¡"
key = "Key1"
mods = "Alt"

[[keyboard.bindings]]
chars = "€"
key = "Key2"
mods = "Alt"

[[keyboard.bindings]]
chars = "#"
key = "Key3"
mods = "Alt"

[[keyboard.bindings]]
chars = "¢"
key = "Key4"
mods = "Alt"

[[keyboard.bindings]]
chars = "∞"
key = "Key5"
mods = "Alt"

[[keyboard.bindings]]
chars = "§"
key = "Key6"
mods = "Alt"

[[keyboard.bindings]]
chars = "¶"
key = "Key7"
mods = "Alt"

[[keyboard.bindings]]
chars = "•"
key = "Key8"
mods = "Alt"

[[keyboard.bindings]]
chars = "ª"
key = "Key9"
mods = "Alt"

[scrolling]
history = 100000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[shell]
args = ["--login"]
program = "/usr/local/bin/fish"

[window]
# decorations = "none"
decorations = "Full"
dynamic_padding = false
opacity = 0.95

[window.dimensions]
columns = 100
lines = 30

[window.padding]
x = 5
y = 5
